### PR TITLE
Refresh launchdarkly client code

### PR DESCRIPTION
**Pull request by chenrui333**
1. Update the `swagger.yaml` with the latest generated `openapi.yaml`
2. `make generate` to generate the client code

### CODE REVIEW

**Comment by mlafeldt** [comment]
That's awesome! Thanks.

Last time I tried updating the lib, go-swagger failed due to some validation error.

Mind telling me what version of `quay.io/goswagger/swagger` you're using?

**Comment by chenrui333** [comment]
Yeah I run into validate issue with `swagger-codegen` v3 too, so I switched to use `swagger-codegen@2` instead. 

For the swagger image, I just use the latest coming along with the `make generate`.

Does that sound right?

**Comment by chenrui333** [comment]
This is the image info:
```
quay.io/goswagger/swagger    latest              1541142c8ca6        2 months ago        536MB
```

**Comment by chenrui333** [comment]
Relates to https://github.com/launchdarkly/ld-openapi/pull/14, have used the branch code to do the `swagger-codegen`.

**Comment by mlafeldt** [comment]
Thank you! Yeah, that PR fixes the issue I mentioned earlier.

Btw, where did you get the swagger.yml file from? The link in the Makefile is broken (and needs to be fixed): https://launchdarkly.github.io/ld-openapi/swagger.yaml

**Comment by chenrui333** [comment]
I actually run `make openapi_yaml` task and grab the `openapi.yaml` from there. Maybe we can build it into the cron job process.

**Pull request merged**
